/* Populate tables */
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Pedro', 'Pascal', 'ppascal@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Juan', 'González', 'jgonzalez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('María', 'Antón', 'manton@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Ariana', 'Fernández', 'afernandez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Laura', 'Gómez', 'lgomez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Óscar', 'Plante', 'oplante@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Paco', 'Fernández', 'pfernandez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Paco', 'Pascal', 'ppascal@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('pedro', 'González', 'jgonzalez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Juan', 'Antón', 'manton@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Ariadna', 'Fernández', 'afernandez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Lucía', 'Gómez', 'lgomez@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Pepe', 'Plante', 'oplante@prueba.com', '2023-02-14', '')
INSERT INTO clientes (nombre, apellido, email, created_at, foto) values ('Álvaro', 'Fernández', 'pfernandez@prueba.com', '2023-02-14', '')